### ISSUE TITLE
Error validating API key in 4.2.4

### ISSUE THREAD

**Issue by long-settlement** [PropelAuth/propelauth-flask#40]
See stack trace below, it seems validate_personal_api_key delegates to propelauth_py (which may be where the root cause is) and fails to deserialize the response into a UserMetadata object.

I can confirm this works in 4.2.3, but not in 4.2.4.

```
  File ".venv/lib/python3.11/site-packages/propelauth_flask/__init__.py", line 328, in validate_personal_api_key
    return self.auth.validate_personal_api_key(api_key_token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/propelauth_py/__init__.py", line 584, in validate_personal_api_key
    return _validate_personal_api_key(self.auth_hostname, self.integration_api_key, api_key_token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/propelauth_py/api/user.py", line 843, in _validate_personal_api_key
    api_key_validation = _validate_api_key(
                         ^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/propelauth_py/api/end_user_api_keys.py", line 266, in _validate_api_key
    user = UserMetadata(
           ^^^^^^^^^^^^^
TypeError: UserMetadata.__init__() got an unexpected keyword argument 'legacy_org_id'
```

**Comment by andrew-propelauth** [comment]
Really sorry about that - there should be a new version now 4.2.5 which fixes the issue (just confirmed on my end). Could you upgrade and let us know if you are still seeing the issue?

**Comment by long-settlement** [comment]
Yep, all sorted, thanks for the quick turnaround!
